use gcc 3.3(.2)

diff --git a/misc/config-env b/misc/config-env
--- a/misc/config-env
+++ b/misc/config-env
@@ -33,15 +33,22 @@ config() {
 			echo 'CC=gcc296'
 		fi 
 
-		if has gcc-3.3; then
-			if has gcc-3.2; then
-				echo 'Using gcc-3.2 instead of 3.3' >&2
-				echo 'CC=gcc-3.2'
-			else 
-				echo 'Cannot use gcc 3.3' >&2
-				exit 1
-			fi
-		fi
+		##
+		## Some poor RedHat users had a busted gcc-3.3 that resulted
+		## in a parser tha couldn't parse anything. 
+		## However, I have success with:
+		## 	gcc version 3.3.2 20030812 (Debian prerelease)
+		## So I won't avoid gcc-3.3 completely.
+		##
+		#if has gcc-3.3; then
+		#	if has gcc-3.2; then
+		#		echo 'Using gcc-3.2 instead of 3.3' >&2
+		#		#echo 'CC=gcc-3.2'
+		#	else 
+		#		echo 'Cannot use gcc 3.3' >&2
+		#		exit 1
+		#	fi
+		#fi
 
 		# Red Hat 7.3: 
 		if [ -d /usr/include/pcap ]; then 
